### ISSUE TITLE
Error when using Highcharts in Angular Universal

### ISSUE THREAD

**Issue by a2441918** [cebor/angular-highcharts#205]
Hi,

I am trying to use highcharts in Angular Universal and I come across this error.

TypeError: extend is not a function
    at C:\Users\a2441918\Code\angular-universal\node_modules\highcharts\highcharts-more.src.js:38:3
    at C:\Users\a2441918\Code\angular-universal\node_modules\highcharts\highcharts-more.src.js:358:3
    at C:\Users\a2441918\Code\angular-universal\node_modules\angular-highcharts\angular-highcharts.umd.js:399:17
    at Array.forEach (<anonymous>)
    at ChartService.initModules (C:\Users\a2441918\Code\angular-universal\node_modules\angular-highcharts\angular-highcharts.umd.js:398:31)
    at new ChartModule (C:\Users\a2441918\Code\angular-universal\node_modules\angular-highcharts\angular-highcharts.umd.js:420:21)
    at _createClass (C:\Users\a2441918\Code\angular-universal\node_modules\@angular\core\bundles\core.umd.js:8435:24)
    at _createProviderInstance (C:\Users\a2441918\Code\angular-universal\node_modules\@angular\core\bundles\core.umd.js:8407:30)
    at initNgModule (C:\Users\a2441918\Code\angular-universal\node_modules\@angular\core\bundles\core.umd.js:8340:36)
    at new NgModuleRef_ (C:\Users\a2441918\Code\angular-universal\node_modules\@angular\core\bundles\core.umd.js:9066:13)

This is my imports:
import {ChartModule, HIGHCHARTS_MODULES} from 'angular-highcharts';
import * as treeMap from 'highcharts/modules/treemap.src';
import * as wordcloud from 'highcharts/modules/wordcloud.src';
import * as boost from 'highcharts/modules/boost.src';
import * as more from 'highcharts/highcharts-more.src';

**Comment by SayakMukhopadhyay** [comment]
I realise its an old issue but I have found that this is not compatible with Universal which is understandable since highcharts manipulates the DOM which is unavailable server side.
