### ISSUE TITLE
Pyramid Chart in AngularJS - Highcharts error #17

### ISSUE THREAD

**Issue by vikkylu** [cebor/angular-highcharts#206]
Hi There,

Below is the piece of code i am using to implementing Pyramid chart of HighCharts in AngularJs.
I haven't faced any issues with highStock chart, but when i am building a pyramid chart i get below error:

I have installed all required modules like highcharts,exporting and funnel. Am i missing any others modules?

angular.js:12520 Error: Highcharts error #17: www.highcharts.com/errors/17
    at Object.a.error (http://localhost:8088/vendor.60827886c949175bdf27.js:136694:178)
    at a.Chart.initSeries (http://localhost:8088/vendor.60827886c949175bdf27.js:136929:415)
    at http://localhost:8088/vendor.60827886c949175bdf27.js:136954:30
    at Array.forEach (<anonymous>)
    at a.each (http://localhost:8088/vendor.60827886c949175bdf27.js:136712:250)
    at a.Chart.firstRender (http://localhost:8088/vendor.60827886c949175bdf27.js:136954:1)
    at a.Chart.<anonymous> (http://localhost:8088/vendor.60827886c949175bdf27.js:136929:304)
    at a.fireEvent (http://localhost:8088/vendor.60827886c949175bdf27.js:136715:191)
    at a.Chart.init (http://localhost:8088/vendor.60827886c949175bdf27.js:136928:91)
    at a.Chart.getArgs (http://localhost:8088/vendor.60827886c949175bdf27.js:136928:16) <section class="app__view ng-scope" ui-view="" flex="" layout="column">

--------------------------------------------------------------------------------------------------------------
var Highcharts = require('highcharts');
require('highcharts-funnel'); 
require('highcharts-exporting');

export default class PricingArchitechtureController {
	constructor($scope, $window, $document, $element,
		 $rootScope) {
		let _this = this,
			chartOptions;

			Highcharts.chart('container', {
				chart: {
					type: 'pyramid'
				},
				title: {
					text: 'Sales pyramid',
					x: -50
				},
				plotOptions: {
					series: {
						dataLabels: {
							enabled: true,
							format: '<b>{point.name}</b> ({point.y:,.0f})',
							color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black',
							softConnector: true
						},
						center: ['40%', '50%'],
						width: '80%'
					}
				},
				legend: {
					enabled: false
				},
				series: [{
					name: 'Unique users',
					data: [
						['Website visits',      15654],
						['Downloads',            4064],
						['Requested price list', 1987],
						['Invoice sent',          976],
						['Finalized',             846]
					]
				}]
			});

			
	}

}

PricingArchitechtureController.$inject = ['$scope', '$window', '$document', '$element',
	'$rootScope'];

Thank you in advance,
Vikram

**Comment by cebor** [comment]
This is a wrapper for Angular 2+ only, sorry.  Use https://github.com/pablojim/highcharts-ng for ng1.

**Comment by vikkylu** [comment]
Hello Cebor, 

So is it possible to achieve the pyramid chart using highcharts-ng directive?

Thank you,
Vikram
