### ISSUE TITLE
TypeError: Cannot read property 'forExport' of undefined after calling getSVG() on ChartObject

### ISSUE THREAD

**Issue by jbowen014** [cebor/angular-highcharts#238]
I know there was a similar issue closed on June 18, but I can't find a solution and am desperate at this point. After calling the getSVG() method on the ChartObject (I'm using Waterfall and Line Charts), I receive an error after trying to navigate to another page. It looks like it's in the Chart.destroy method.

It looks like Highcharts fixed something in issue 8643 (https://github.com/highcharts/highcharts/issues/8643) and changed what the destroy method returns in 9232 (https://github.com/highcharts/highcharts/issues/9232). The destroy method now returns undefined instead of an empty object.

I'm using version 7.0.2 of angular-highcharts and 6.2.0 of highcharts and Angular 7. Thank you in advance for your help.

Here is the call stack:

"Error: Uncaught (in promise): TypeError: Cannot read property 'forExport' of undefined
TypeError: Cannot read property 'forExport' of undefined
    at a.Chart.destroy (http://localhost:49896/vendor.js:78077:439)
    at Chart.push../node_modules/angular-highcharts/fesm5/angular-highcharts.js.Chart.destroy (http://localhost:49896/vendor.js:70422:22)
    at ChartDirective.push../node_modules/angular-highcharts/fesm5/angular-highcharts.js.ChartDirective.destroy (http://localhost:49896/vendor.js:70620:24)
    at ChartDirective.push../node_modules/angular-highcharts/fesm5/angular-highcharts.js.ChartDirective.ngOnDestroy (http://localhost:49896/vendor.js:70599:14)
    at callProviderLifecycles (http://localhost:49896/vendor.js:53320:18)
    at callElementProvidersLifecycles (http://localhost:49896/vendor.js:53288:13)
    at callLifecycleHooksChildrenFirst (http://localhost:49896/vendor.js:53278:29)
    at destroyView (http://localhost:49896/vendor.js:54340:5)
    at callViewAction (http://localhost:49896/vendor.js:54466:13)
    at execEmbeddedViewsAction (http://localhost:49896/vendor.js:54409:17)
    at resolvePromise (http://localhost:49896/polyfills.js:7152:31)
    at resolvePromise (http://localhost:49896/polyfills.js:7109:17)
    at http://localhost:49896/polyfills.js:7211:17
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:49896/polyfills.js:6759:31)
    at Object.onInvokeTask (http://localhost:49896/vendor.js:48511:33)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:49896/polyfills.js:6758:36)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:49896/polyfills.js:6526:47)
    at drainMicroTaskQueue (http://localhost:49896/polyfills.js:6933:35)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (http://localhost:49896/polyfills.js:6838:21)
    at ZoneTask.invoke (http://localhost:49896/polyfills.js:6823:48)"

**Comment by cebor** [comment]
Which versions of angular and angular-highcharts do you use?

Undefined charts should be catched by:

https://github.com/cebor/angular-highcharts/blob/master/projects/angular-highcharts/src/lib/chart.ts#L89

**Comment by jbowen014** [comment]
I'm using version 7.0.2 of angular-highcharts, 6.2.0 of highcharts, and Angular 7.

Thank you

**Comment by AntiAsko** [comment]
It seems this issue still occurs with angular-highcharts@9.0.2, angular@9.0.6 and highcharts@8.0.4. When exporting and then navigate to another page.

`Error: Uncaught (in promise): TypeError: Cannot read property 'forExport' of undefined
TypeError: Cannot read property 'forExport' of undefined
    at d.Chart.destroy (highcharts.js:315)
    at Chart.push../node_modules/angular-highcharts/__ivy_ngcc__/fesm5/angular-highcharts.js.Chart.destroy (query-viewer-query-viewer-module.js:193)
    at ChartDirective.push../node_modules/angular-highcharts/__ivy_ngcc__/fesm5/angular-highcharts.js.ChartDirective.destroy (query-viewer-query-viewer-module.js:414)
    at ChartDirective.push../node_modules/angular-highcharts/__ivy_ngcc__/fesm5/angular-highcharts.js.ChartDirective.ngOnDestroy (query-viewer-query-viewer-module.js:389)
    at executeOnDestroys (core.js:9279)
    at cleanUpView (core.js:9208)
    at destroyViewTree (core.js:9008)
    at destroyLView (core.js:9161)
    at RootViewRef.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.ViewRef.destroy (core.js:9894)
    at ComponentRef.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.ComponentRef.destroy (core.js:23037)
    at RouterOutlet.push../node_modules/@angular/router/__ivy_ngcc__/fesm5/router.js.RouterOutlet.deactivate (router.js:5212)
    at ActivateRoutes.push../node_modules/@angular/router/__ivy_ngcc__/fesm5/router.js.ActivateRoutes.deactivateRouteAndOutlet (router.js:2270)
    at ActivateRoutes.push../node_modules/@angular/router/__ivy_ngcc__/fesm5/router.js.ActivateRoutes.deactivateRouteAndItsChildren (router.js:2250)
    at router.js:2267
    at forEach (router.js:707)
    at resolvePromise (zone.js:832) [angular]
    at resolvePromise (zone.js:784) [angular]
    at :4200/polyfills.js:907:21 [angular]
    at Object.onInvokeTask (core.js:27788) [angular]
    at drainMicroTaskQueue (zone.js:601) [<root>]
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:507) [<root>]
    at invokeTask (zone.js:1671) [<root>]
    at HTMLAnchorElement.globalZoneAwareCallback (zone.js:1708) [<root>]`

**Comment by AntiAsko** [comment]
Quick fix I did locally and fixes the issue:

`    /**
     * @private
     * @return {?}
     */
    ChartDirective.prototype.destroy = /**
     * @private
     * @return {?}
     */
    function () {
        console.log(this.chart);
        if (this.chart && this.chart.ref && Object.keys(this.chart.ref).length !== 0 && (this.chart instanceof Chart || this.chart instanceof StockChart || this.chart instanceof MapChart)) {
            console.log(Object.keys(this.chart.ref));
            this.chart.destroy();
        }
    };`

**Comment by cebor** [comment]
@AntiAsko thx, im trying to get this fix in.

**Comment by AntiAsko** [comment]
@cebor Glad I could be of help. If there is a way to help feel free to let me know

**Comment by cebor** [comment]
@AntiAsko published a new release, can you check if its working for you?

**Comment by cebor** [comment]
I think its fixed, just struggling with these new github actions ^^

**Comment by AntiAsko** [comment]
@cebor Latest version fixed the issue. Thank you very much for the quick fix. Very much appreciated!

**Comment by sbgnit23** [comment]
> @AntiAsko thx, im trying to get this fix in.

which version contains the fix

**Comment by GurlWhoCodesAlot** [comment]
do we have any fix for below versions?
we cant afford changing versions for now
        "highcharts": "7.1.2",
        "@angular/core": "11.2.14"
        "angular-highcharts": "8.0.1",
