### ISSUE TITLE
Add support ESbuild imports

### ISSUE THREAD

**Issue by kirill-borisyonok** [cebor/angular-highcharts#397]
https://angular.dev/tools/cli/esbuild#esm-default-imports-vs-namespace-imports

My npm versions:
"@angular/core": "17.1.2",
"@angular-devkit/build-angular": "17.1.2",
"angular-highcharts": "17.0.0",

Error: Unable to resolve specifier 'highcharts/highcharts-gantt' imported from http://localhost:4200/angular_highcharts-17_0_0-dev.js
    at throwUnresolved (es-module-shims.js:442:11)
    at _resolve (es-module-shims.js:399:71)
    at es-module-shims.js:848:32
    at Array.map (<anonymous>)
    at es-module-shims.js:844:45
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Zone2.run (zone.js:129:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Zone2.runTask (zone.js:173:47)

**Comment by andrei4ik1997** [comment]
I have still problem. @cebor pls fix it

**Comment by andrei4ik1997** [comment]
@cebor We also opened issue to Highcharts https://github.com/highcharts/highcharts/issues/20616

**Comment by andrei4ik1997** [comment]
@cebor We can do this solution in library https://github.com/highcharts/highcharts/issues/20616#issuecomment-1945599576  ?Or are there other suggestions?
